<body> 
     <h1>Modifying HTML with JavaScript</h1>  

     <p id="para1">JavaScript is powerful!</p> 
     <p id="para2">It can manipulate HTML.</p> 
     <script type="text/javascript"> 
          document.getElementById("para2").style.color = "red";

     </script>
</body>
